---
- name: Install Filebeat
  become: true
  apt:
    deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb
    state: present

- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: filebeat.service
    state: started

- name: Copy Filebeat config
  become: true
  copy:
    src: /home/dmitrym/diplom/ansible/roles/filebeat/templates/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
    owner: dmitrym
    group: root

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Enable and restart filebeat
  systemd:
    name: filebeat.service
    enabled: true
    masked: no
    state: restarted
