---
# - name: Install java
#   become: true
#   apt:
#     name: openjdk-19-jre-headless #openjdk-11-jdk
#     state: latest

- name: Install elasticsearch
  become: true
  apt:
    deb: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.14-amd64.deb
    state: present

- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: elasticsearch.service
    state: started

- name: Copy Elasticsearch config
  become: true
  copy:
    src: /home/dmitrym/diplom/ansible/roles/elasticsearch/templates/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644
    owner: dmitrym
    group: root

- name: Enable and restart elasticsearch
  become: true
  ansible.builtin.systemd:
    name: elasticsearch.service
    enabled: true
    masked: no
    state: restarted
