---
- name: Install elasticsearch
  become: true
  apt:
    deb: https://ftp.yandex.ru/mirrors/elastic/8/pool/main/e/elasticsearch/elasticsearch-8.0.0-amd64.deb
    state: present

- name: Copy Elasticsearch config
  become: true
  copy:
    src: /home/dmitrym/diplom/ansible/roles/elasticsearch/templates/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644
    owner: dmitrym
    group: root

- name: Enable and restart elasticsearch
  become: true
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    masked: no
    state: restarted
