---
- name: Update package cache
  apt: update_cache=yes

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Change index.html file
  template:
    src: /home/dmitrym/diplom/ansible/roles/web/templates/index.html.j2
    dest: /var/www/html/index.html
    mode: 0555
#  notify: Restart nginx

- name: Change nginx.conf file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0555

- name: Enable and restart nginx
  systemd:
    name: nginx
    enabled: true
    masked: no
    state: restarted
