- name: restart zabbix-server
  service:
    name: zabbix-server-pgsql
    state: restarted
    enabled: true

- name: restart zabbix-agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: true
