---
- name: deploy zabbixserver
  hosts: zabbixserver
  become: true
  vars:
    postgres_password: postgres
  roles:
    - zabbixserver

- name: deploy elasticsearch
  hosts: elasticsearch
  become: true
  roles:
    - elasticsearch

- name: deploy kibana
  hosts: kibana
  become: true
  roles:
    - kibana

- name: deploy web servers
  hosts: web
  become: true
  roles:
    - web
    - filebeat

- name: deploy zabbixagent
  hosts:
    - web
    - elasticsearch
    - kibana
    - bastion
  become: true
  roles:
    - zabbixagent
