---
- name: Install zabbix agent
  apt:
    name: zabbix-agent
    state: present
  become: true

- name: Replace config zabbix agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server=(.*)"
    line: "Server=192.168.10.3"
    state: present
  become: true

- name: Update config zabbix agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive=(.*)"
    line: "ServerActive=192.168.10.3"
    state: present
  become: true

- name: Enable and restart zabbix agent
  systemd:
    name: zabbix-agent
    enabled: true
    masked: false
    state: restarted
  become: true
