---
- name: Install zabbix agent
  apt:
    name: zabbix-agent
    state: present
  become: true

- name: Replace config zabbix agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server=(.*)"
    line: "Server=192.168.10.3"
    state: present
  become: true

- name: Update config zabbix agent
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive=(.*)"
    line: "ServerActive=192.168.10.3"
    state: present
  become: true

- name: Enable and restart zabbix agent
  systemd:
    name: zabbix-agent
    enabled: true
    masked: false
    state: restarted
  become: true

# - name: Download zabbixagent
#   apt:
#     deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"

# - name: update apt packages
#   apt:
#     force_apt_get: true
#     update_cache: yes
#     upgrade: dist
#   become: true

# - name: Install zabbix-agent
#   apt:
#     pkg:
#       - zabbix-agent
#   become: true


# - name: Update repository
#   apt:
#     update_cache: yes

# # - name: Install zabbixagent
# #   apt:
# #     name: zabbix-agent
# #     state: present

# - name: Copy zabbix_agentd config
#   template:
#     src: zabbix_agentd.conf
#     dest: /etc/zabbix/zabbix_agentd.conf
#     owner: root
#     group: root
#     mode: '0644'
#     backup: yes

# - name: Enable and restart zabbix agent
#   systemd:
#     name: zabbix-agent
#     enabled: true
#     masked: no
#     state: restarted
