---
- name: Install Kibana
  become: true
  apt:
    deb: https://ftp.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.0.0-amd64.deb
    state: present

- name: Copy Kibana config
  become: true
  copy:
    src: /home/dmitrym/diplom/ansible/roles/kibana/templates/kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: 0644
    owner: dmitrym
    group: root

- name: Enable and restart kibana
  systemd:
    name: kibana
    enabled: true
    masked: no
    state: restarted
