# - name: Update package cache
#   apt:
#     update_cache: yes

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: nginx enable
  become: true
  systemd:
    name: nginx
    enabled: true

- name: Install ufw
  become: true
  apt:
    name: ufw
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable UFW
  become: true
  ufw:
    state: enabled

- name: Allow HTTP
  ufw:
    rule: allow
    port: http
    proto: tcp
    state: enabled

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Reloaded UFW
  become: true
  ufw:
    state: reloaded
    
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Zabbix Server
  apt:
    name: zabbix-server-pgsql
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Zabbix Agent
  apt:
    name: zabbix-agent
    state: present

- name: Create database and user for Zabbix
  postgresql_db:
    name: zabbix
    login_user: postgres
    login_password: postgres

- name: Setting database for Zabbix Server
  shell: zcat /usr/share/doc/zabbix-server-pgsql/create.sql.gz | psql -h localhost -d zabbix -U zabbix

- name: Setting configure Zabbix Server
  template:
    src: /home/dmitrym/diplom/ansible/roles/zabbix-server/templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    mode: 0555
  notify: restart zabbix-server

- name: Setting configure Zabbix Agent
  template:
    src: /home/dmitrym/diplom/ansible/roles/zabbix-server/templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: 0555
  notify: restart zabbix-agent
