---
- name: Update package cache
  apt: update_cache=yes

- name: create a directory
  ansible.builtin.file:
   path: /etc/zabbix-files
   state: directory
   mode: "0755"
  become: true

- name: download the zabbix
  ansible.builtin.get_url:
   url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
   dest: /etc/zabbix-files
  become: true

- name: Install the zabbix package
  apt:
    deb: /etc/zabbix-files/zabbix-release_6.0-4+ubuntu22.04_all.deb
  become: true


# - name: download and install the zabbix package
#   ansible.builtin.apt:
#     deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
#   become: true

- name: update apt packages
  apt:
    # force_apt_get: true
    update_cache: yes
    upgrade: dist
  become: true

- name: Install zabbix
  apt:
    pkg:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent
  become: true


- name: Install mysql database and dependencies
  apt:
    name:
      - mysql-server
      - python3-pip
      - libmysqlclient-dev
      - python3-dev
      - python3-mysqldb
    state: present
  become: true

- name: Enable and reload mysql
  systemd:
    name: mysql
    enabled: true
    masked: no
    state: restarted
  become: true

- name: Create User
  community.mysql.mysql_user:
    name: zabbix
    password: "{{password_db}}"
    priv: "*.*:ALL,GRANT"
    state: present

- name: Create database for mysql
  community.mysql.mysql_db:
    name: zabbix
    encoding: utf8mb4
    collation: utf8mb4_bin
    state: present

- name: Search for server.sql
  stat:
    path: /usr/share/zabbix-sql-scripts/mysql/server.sql
  register: result

- name: Extract .gz into /tmp
  ansible.builtin.shell:
    cmd: gunzip /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  when: not result.stat.exists

- name: Import preset
  community.mysql.mysql_db:
    name: zabbix
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql
  when: not result.stat.exists

- name: Set new database password for mysql database
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    insertafter: "DBPassword="
    line: DBPassword={{password_db}}

- name: Copy nginx config
  become: true
  ansible.builtin.copy:
    src: /home/dmitrym/diplom/ansible/roles/zabbixserver/templates/nginx.conf
    dest: /etc/zabbix/
    # dest: /etc/nginx/nginx.conf
    mode: 0644


- name: Enable and restart zabbix-server
  systemd:
    name: zabbix-server
    enabled: true
    masked: no
    state: restarted
  become: true

- name: Enable and restart zabbix-agent
  systemd:
    name: zabbix-agent
    enabled: true
    masked: no
    state: restarted
  become: true

- name: Enable and restart nginx
  systemd:
    name: nginx
    enabled: true
    masked: no
    state: restarted
  become: true

- name: Enable and restart php
  systemd:
    name: php8.1-fpm
    enabled: true
    masked: no
    state: restarted
  become: true

#7.4
